pipeline {
    agent { docker { image 'node:8.15.0-jessie' } }
    environment {
        HOME = '.'
    }
    stages {
        stage('Build') {
            steps {
                sh "npm cache clean && npm start -- --reset-cache"
                sh "npm install"
                sh "npm -version"

            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}